apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: jenkins
  source:
    repoURL: 'https://github.com/leoprz606/gitops.git'
    targetRevision: jenkins
    path: apps/jenkins  # Where your Jenkins manifests are located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins  # Namespace where you want Jenkins to be deployed
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true