apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-media-pv
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/media/jenkins"
